"""`.memoignore` handling — same syntax as `.gitignore`, powered by pathspec."""

from __future__ import annotations

import os
from pathlib import Path

import pathspec

from .config import IGNORE_FILENAME

# Written by `memo init` when a repo has no .memoignore yet. Indexing build output
# and vendored/minified assets is actively harmful: it inflates the graph with
# thousands of junk symbols that then crowd out real code in ranked results.
DEFAULT_MEMOIGNORE = """\
# .memoignore — gitignore syntax. Files matched here are skipped by memo's indexer.
# Generated by `python -m memo.cli init`; edit freely, memo will not overwrite it.

# VCS internals — nothing indexable, and .git can hold a huge object tree
.git/
.svn/
.hg/

# Dependencies / build output
node_modules/
bin/
obj/
dist/
build/
out/
*.egg-info/
.venv/
venv/
__pycache__/
packages/
TestResults/
.vs/
.idea/
wwwroot/lib/

# The cache itself
.memo/

# Claude Code worktrees — a parallel-session checkout of the SAME repo, living
# inside it. Indexing it duplicates every symbol under a second path: a `brief`/
# `callers` query then returns two near-identical hits for one real function, and
# an agent has to spend tokens figuring out (or worse, not realizing) that one of
# them is stale. Measured directly: every session in a real multi-run benchmark on
# a repo with an active worktree had to manually call this out as "ignore this
# copy, it's the worktree" — pure avoidable waste.
.claude/worktrees/

# Minified / generated assets
*.min.js
*.min.css
*-bundle.js
*.designer.cs
*.Designer.vb
*.g.cs
*.g.i.cs
*.generated.cs
Reference.cs
"""


# pathspec renamed this factory: "gitwildmatch" is deprecated (it warns on every
# pattern compiled, which is noisy at repo scale) and slated for removal, but
# "gitignore" doesn't exist on older releases we still support. Resolve once, prefer new.
def _pattern_factory() -> str:
    try:
        from pathspec.util import lookup_pattern

        lookup_pattern("gitignore")
        return "gitignore"
    except Exception:
        return "gitwildmatch"


_FACTORY = _pattern_factory()


def load_ignore_spec(root: Path) -> pathspec.PathSpec | None:
    """Load a `.memoignore` from `root`, returning a compiled spec or None."""
    ignore_file = root / IGNORE_FILENAME
    if not ignore_file.is_file():
        return None
    try:
        lines = ignore_file.read_text(encoding="utf-8").splitlines()
    except OSError:
        return None
    try:
        return pathspec.PathSpec.from_lines(_FACTORY, lines)
    except Exception as exc:
        # A malformed pattern shouldn't abort indexing, but silently ignoring the whole
        # file would silently index everything the user meant to exclude.
        raise ValueError(f"{ignore_file}: invalid ignore pattern ({exc})") from exc


def is_ignored(spec: pathspec.PathSpec | None, root: Path, path: Path) -> bool:
    """Return True if `path` (under `root`) is matched by the ignore spec.

    Deliberately avoids `Path.resolve()`. This is called once per walked file — 26,204
    of them in a repo whose 541 source files we actually want — and resolve() is a
    filesystem round-trip each time; it accounted for 12.25s of an 18s re-index.
    Paths from `Path.rglob(root)` are already rooted at `root`, so a plain
    `relative_to` suffices, with `os.path.relpath` as the textual fallback.
    """
    if spec is None:
        return False
    try:
        rel = path.relative_to(root)
    except ValueError:
        try:
            rel = Path(os.path.relpath(path, root))
        except ValueError:
            return False  # different drive -> not governed by this ignore file
    return spec.match_file(rel.as_posix())
