"""Render the canonical guide into each target's rule-file format, idempotently.

The hard requirement here is that `memo init` must be safe to re-run against a repo
that ALREADY has an `AGENTS.md` or `.github/copilot-instructions.md` full of the
team's own instructions — which is the common case, not the edge case. So memo
claims only a delimited region:

    <!-- BEGIN memo v0.2.0 sha=... -->
    ...generated guidance...
    <!-- END memo -->

`upsert()` replaces that region in place and never touches a byte outside it. The
`sha=` in the opening marker is the hash of the body memo last wrote, which lets us
tell "memo's own output is out of date" (safe to replace) apart from "a human edited
inside the block" (refuse, and require --force). Without that distinction, a routine
re-index would silently eat someone's edits.

Files memo owns outright — Cursor's `.mdc` and the Claude Code skill — are the
exception: they are written whole. That also guarantees the YAML frontmatter stays on
line 1, which both formats require.
"""

from __future__ import annotations

import hashlib
import re

from . import __version__
from .guide import render_guide, render_stub
from .targets import Target

END = "<!-- END memo -->"

_BEGIN_RE = re.compile(r"^<!-- BEGIN memo\b.*?-->[ \t]*$", re.M | re.S)
_END_RE = re.compile(r"^" + re.escape(END) + r"[ \t]*$", re.M)
_SHA_RE = re.compile(r"\bsha=([0-9a-f]{6,64})\b")

# Deliberately NOT a setup section. An earlier version opened every generated file with
# "Index this repo once: python -m memo.cli init" — but the agent only ever reads these
# files *because* init already ran, and following that instruction would make it
# overwrite the very file it was reading. Refresh guidance now lives in the guide's
# trust section (`memo status`), and rule 5 forbids init/clear outright.


def _sha(text: str) -> str:
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()[:12]


def render_body(target: Target) -> str:
    """The guidance text for `target`, without frontmatter or managed-block markers.

    Which of the two bodies a target gets is decided by when its host agent loads the
    file, not by how much there is to say: `stub` for anything unconditional, the full
    guide only where loading is deferred until the agent asks. See targets.py.
    """
    if target.style == "stub":
        return render_stub(target.native)
    return render_guide(target.native)


def wrap(body: str) -> str:
    """Fence `body` in versioned, hash-stamped managed-block markers."""
    body = body.strip()
    begin = (
        f"<!-- BEGIN memo v{__version__} sha={_sha(body)} — generated by "
        "`python -m memo.cli init`; edits inside this block are overwritten -->"
    )
    return f"{begin}\n{body}\n{END}"


def _split(text: str) -> tuple[int, int, str, str | None] | None:
    """Locate memo's managed block: (start, end, inner_text, declared_sha) or None."""
    m1 = _BEGIN_RE.search(text)
    if not m1:
        return None
    m2 = _END_RE.search(text, m1.end())
    if not m2:
        return None  # unterminated marker: treat as absent rather than guess an extent
    sm = _SHA_RE.search(m1.group(0))
    return m1.start(), m2.end(), text[m1.end():m2.start()], sm.group(1) if sm else None


def upsert(existing: str | None, body: str, *, force: bool = False) -> tuple[str, str]:
    """Insert or refresh memo's managed block inside `existing`.

    Returns (new_text, status) where status is one of:
      created   — no block was present (file absent, empty, or memo-free)
      unchanged — the block already holds exactly this body
      updated   — the block was memo's own older output, replaced in place
      conflict  — the block was edited by hand; refused unless force=True

    Content outside the markers is preserved byte-for-byte in every case.
    """
    block = wrap(body)
    if not existing or not existing.strip():
        return block + "\n", "created"

    found = _split(existing)
    if found is None:
        # Append, normalizing to exactly one blank line before our block.
        sep = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
        return existing + sep + block + "\n", "created"

    start, end, inner, declared = found
    if inner.strip() == body.strip():
        return existing, "unchanged"
    if declared and _sha(inner) != declared and not force:
        return existing, "conflict"
    return existing[:start] + block + existing[end:], "updated"


def check(existing: str | None, target: Target) -> str:
    """Report a rule file's state without touching it: missing/current/stale/edited.

    Reuses upsert's decision logic so `memo status` can never disagree with what
    `memo init` would actually do.
    """
    if existing is None:
        return "missing"
    if target.exclusive:
        return "current" if existing == file_text(target) else "stale"
    _, status = upsert(existing, render_body(target))
    return {"created": "missing", "unchanged": "current",
            "updated": "stale", "conflict": "edited"}[status]


def file_text(target: Target) -> str:
    """Full file content for a target memo owns outright (frontmatter + body)."""
    body = render_body(target)
    if target.frontmatter:
        return f"{target.frontmatter}\n\n{body.strip()}\n"
    return body.strip() + "\n"
